[CT-46] HomeViewModel Unit Test
f-lab-edu/chart-trainer pull request #64
Opened 2024-06-29 08:26 UTC by nosorae

2024-06-29 08:52 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +//    fun initiate_state_is_loading() = runTest {
Loading 을 테스트할 방법을 아직 찾는중입니다.

StateFlow가 마지막 값을 가지니 실제로는 Loading 이 StateFlow.update 로 업데이트되긴 하지만 테스트할 때는 Success가 잡힙니다.

2024-07-01 13:17 UTC, omjoonkim requested changes
> 기존은 모델에 람다를 전달하는 방식이었는데 assertEquals 가 정상작동하기 어렵게하여 click에 필요한 데이터를 가지는 data class를 따로 만들어 Screen 을 다녀오는 방식으로 변경했습니다.

이런 부분들이 바로 사용하기에는 편하나 구조상으로는 좋지 않은, 테스트 코드를 작성하다보면 깨닫게 되는  지점중에 하나입니다. ㅎㅎ

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +//    fun initiate_state_is_loading() = runTest {
코루틴에서 방출된 값을 검증 할 수 있는 방법을 제공해주면 좋을텐데요. 만약 없다면 방출된 값을 어딘가에 담아두었다가 마지막에 검증하는 방식을 주로 사용합니다.

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        createUserInfoUi()
Q; 이 함수는 무엇을 실행하고 무엇을 어떻게 검증하는 걸까요?

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        runTest {
nit; 인덴트가 많아지지 않도록 runTest는 위로 붙이는게 가독성에 더 좋을 것 같습니다.

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +            chartTrainerPreferencesDataSource.updateLastChartGameId(1L)
nit; 검증에 필요한 값을 변수로 선언하여 활용하면 코드 가독성과 수정에 있어 좀 더 편해집니다.

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +    fun bottom_button_state_is_new_game_when_last_chart_game_id_is_null() =
Q; 아래 코드만을보고 chart_game_id가 null인 것을 알 수 있을까요?

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +class HomeViewHomeModelTest {
p3; 전체적으로 테스트 함수명과 테스트 케이스 내부의 코드가 매치가 잘 되지 않습니다. 어떻게 값이 설정되고 변경되는지 파악하기가 어려운 것 같아요. 또 기본적인 컨벤션(given/when/then)등의 사용이 적절하게 되어있지 않은 것 같습니다.

2024-07-01 13:17 UTC, omjoonkim commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/UserInfoUiTest.kt
> +        userInfoUi = createUserInfoUi(
P2; 한 함수에서 여러 케이스의 검증을 하는 것보다 각 케이스 마다 테스트 함수를 만드는 것이 좋습니다.

2024-07-01 13:24 UTC, f-lab-nathan requested changes

2024-07-01 13:24 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +class HomeViewHomeModelTest {
p3; 전체적으로 테스트 함수명과 테스트 케이스 내부의 코드가 매치가 잘 되지 않습니다. 어떻게 값이 설정되고 변경되는지 파악하기가 어려운 것 같아요. 또 기본적인 컨벤션(given/when/then)등의 사용이 적절하게 되어있지 않은 것 같습니다.

2024-07-01 13:24 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +//    fun initiate_state_is_loading() = runTest {
코루틴에서 방출된 값을 검증 할 수 있는 방법을 제공해주면 좋을텐데요. 만약 없다면 방출된 값을 어딘가에 담아두었다가 마지막에 검증하는 방식을 주로 사용합니다.

2024-07-01 13:24 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        createUserInfoUi()
Q; 이 함수는 무엇을 실행하고 무엇을 어떻게 검증하는 걸까요?

2024-07-01 13:24 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        runTest {
nit; 인덴트가 많아지지 않도록 runTest는 위로 붙이는게 가독성에 더 좋을 것 같습니다.

2024-07-01 13:24 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +            chartTrainerPreferencesDataSource.updateLastChartGameId(1L)
nit; 검증에 필요한 값을 변수로 선언하여 활용하면 코드 가독성과 수정에 있어 좀 더 편해집니다.

2024-07-01 13:24 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +    fun bottom_button_state_is_new_game_when_last_chart_game_id_is_null() =
Q; 아래 코드만을보고 chart_game_id가 null인 것을 알 수 있을까요?

2024-07-01 13:25 UTC, f-lab-nathan commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/UserInfoUiTest.kt
> +        userInfoUi = createUserInfoUi(
P2; 한 함수에서 여러 케이스의 검증을 하는 것보다 각 케이스 마다 테스트 함수를 만드는 것이 좋습니다.

2024-07-01 14:31 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +//    fun initiate_state_is_loading() = runTest {
말씀을 듣고 생각해본 방법은 
핫 플로인 StateFlow 를 다시 콜드 플로우로 변환한다음에 두 번째 값을 캡쳐하면 될 것 같습니다.
시도해보겠습니다. 감사합니다.

2024-07-01 14:35 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/UserInfoUiTest.kt
> +        userInfoUi = createUserInfoUi(
오 넵 개별 테스트로 다루겠습니다.

2024-07-01 14:38 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +class HomeViewHomeModelTest {
넵! 말씀주신 방향으로 함수명과 테스트 구성을 수정해보겠습니다. 

(Unit Testing 책 3장에서 메소드 작명 베스트 프랙티스를 읽어봐도 아직 감이 잘 오지 않습니다.. 🥲 )

2024-07-01 14:44 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        createUserInfoUi()
저것은 실수입니다. HomeViewModelTest에 작성하려다가 아예 UserInfoUiTest 라는 클래스를 새로 만들어거 거기서 진행했습니다.

2024-07-01 14:48 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        runTest {
넵!

 .editorconfig 의 라인 길이 제한 설정을 늘려야할 것 같은데  문제는 변경점이 (기존에 라인 제한으로 줄바꿈한 코드들이 줄바꿈 되지 안음으로써) 많아져 리뷰하는데 잡음이 많아진다는 문제가 있습니다. 

ktlint 를 사용하니 이런 단점이 있네요.

이거는 다른 곳에서 따로 진행하는 게 좋겠어서 따로 잔이슈(특정 이슈안의 TODO)로 남겨 놓겠습니다.

2024-07-01 14:49 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +            chartTrainerPreferencesDataSource.updateLastChartGameId(1L)
오 넵 수정하겠습니다!

2024-07-01 14:50 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +    fun bottom_button_state_is_new_game_when_last_chart_game_id_is_null() =
아뇨 명시적으로 변경하는 게 좋겠습니다.

2024-07-02 07:08 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +    fun bottom_button_state_is_new_game_when_last_chart_game_id_is_null() =
우선 null을 준다는 것을 명시적으로 표현해봤습니다. 

그런데 마지막 플레이한 차트게임 id가 null일 때만 NewGame 상태라는 것을 나타내기 위해
id에 값을 줘서 assert 하고 다시 null을 줘서 assert 하는 건 어떤지 궁금합니다!

2024-07-02 08:47 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +class HomeViewHomeModelTest {
함수명은 업데이트해봤습니다! 대부분의 변경은.. 함수 이름 앞에 test_ 를 붙인 게 다입니다. 
나름대로 {결과}_when_{행위} 라는 '사실'을 적으려고했습니다. 멘토링 시간까지 좀 더 나은 테스트 메서드 이름을 고민해보겠습니다.

2024-07-02 08:50 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +class HomeViewHomeModelTest {
given/when/then 패턴에서 given 을 적기 애매한 부분이(심지어 의도를 알 수없어 가독성을 해치는 경우가) 있다고 생각했습니다.

아무런 세팅을 하지않고 사용자가 특정 액션을 하면 특정 상태로 변경되어야하는 경우에도 Given을 적어주는 게 좋을까요? (ex. 버튼클릭하면 이전 상태가 뭐가 됐든 다이얼로그가 나와야함)

이것도 멘토링 시간까지 더 고민 해보겠습니다.

2024-07-07 11:01 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        createUserInfoUi()
제거했습니다!

2024-07-07 11:02 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +        runTest {
max_line_length 수정해서 해결했습니다.

2024-07-07 12:24 UTC, nosorae commented on app/src/test/java/com/yessorae/chartrainer/presentation/home/HomeViewHomeModelTest.kt
> +class HomeViewHomeModelTest {
함수명 멘토링에서 알려주신 컨벤션으로 모두 업데이트 했습니다!

2024-07-07 14:48 UTC, f-lab-nathan commented
수고하셨습니다. 👍
처음보다 확실히 좋아졌네요. :)

2024-07-07 14:48 UTC, merged